[server]
    output = "direct"
    storage = "hdfs"
    host = "0.0.0.0"
    port = 8089

[input.nsq]
    enable = false
    nsqd = "192.168.0.135:4161"
    topic = "file"
    channel = "client"

[output.nsq]
    nsqd = "192.168.0.135:4150"
    topic = "file"

[storage.mongodb]
    url = "192.168.0.135:27017"

[storage.file]
    directory = "uploads"

[storage.webhdfs]
    url = "localhost:50070"

[storage.hdfs]
    url = "0.0.0.0:9000"
    user = "WXH"
