[server]
    output = "nsq"
    storage = "mongodb"
    host = "0.0.0.0"
    port = 8080

[input.nsq]
    enable = true
    nsqd = "192.168.0.135:4161"
    topic = "file"
    channel = "client"

[output.nsq]
    nsqd = "192.168.0.135:4150"
    topic = "file"

[storage.mongodb]
    mongo = "192.168.0.135:27017"

[storage.file]
     directory = "uploads"


