[server]
    output = "direct"
    storage = "file"
    host = "0.0.0.0"
    port = 8089
    restServer = "http://127.0.0.1:8080/mpp/"

[input.nsq]
    enable = false
    nsqd = "192.168.0.135:4161"
    topic = "file"
    channel = "client"

[output.nsq]
    nsqd = "192.168.0.135:4150"
    topic = "file"

[input.mongodb]
    url = "192.168.0.135:27017"
    md5 = "87847b63d1da669dbc8b52670d03b0c5"

[storage.mongodb]
    #url = "192.168.10.10:27017"
    url = "192.168.10.11:10004"

[storage.file]
    directory = "uploads"

[storage.webhdfs]
    url = "localhost:50070"

[storage.hdfs]
    url = "0.0.0.0:9000"
    user = "WXH"
